### ISSUE TITLE
Upload Wireframes

### ISSUE THREAD

**Issue by jobannon** [jobannon/upvote_ui#1]
### Idea Show Page ![idea show page](https://user-images.githubusercontent.com/50811220/74800132-c6f57f00-528f-11ea-983f-9701ef73ce73.png)

**Comment by freeheeling** [comment]
- ![splash](https://user-images.githubusercontent.com/50811220/74799940-35860d00-528f-11ea-89d7-279304af3008.png)
- ![dashboard](https://user-images.githubusercontent.com/50811220/74800002-623a2480-528f-11ea-8e48-d8d162003b0f.png)
- ![idea CUD page](https://user-images.githubusercontent.com/50811220/74800101-adecce00-528f-11ea-91a8-65896c4325dc.png)
- ![idea show page](https://user-images.githubusercontent.com/50811220/74800132-c6f57f00-528f-11ea-983f-9701ef73ce73.png)
