### ISSUE TITLE
Architecture Design

### ISSUE THREAD

**Issue by freeheeling** [jobannon/upvote_ui#11]

**Comment by jobannon** [comment]
<img width="602" alt="Screen Shot 2020-02-27 at 5 47 43 PM" src="https://user-images.githubusercontent.com/16090626/75500282-b927b400-5989-11ea-88df-7329883e35d3.png">

**Comment by jobannon** [comment]
![upvotetech](https://user-images.githubusercontent.com/16090626/75500418-1cb1e180-598a-11ea-8571-797be8c32ece.png)
